### ISSUE TITLE
`natural` parser parses 0

### ISSUE THREAD

**Issue by simonyangme** [ekmett/parsers#56]
In fact, it accepts any number of 0s, and returns 0 as a result, when the documentation specifies that it should only parse positive integers.

**Comment by ekmett** [comment]
I should change the documentation to say non-negative.

**Comment by simonyangme** [comment]
Yeah I think clarifying that would be nice as I've learned natural means different things for different people. Thanks!

**Comment by ekmett** [comment]
Fixed.
