### ISSUE TITLE
new parsers not on hackage..

### ISSUE THREAD

**Issue by mimi1vx** [ekmett/parsers#63]
please update parser on hackage to 0.12.4

**Comment by bgamari** [comment]
Indeed a release would be nice.

**Comment by ocramz** [comment]
Paging Eric @glguy : )  this package version is needed for bumping `inline-c` to GHC 8, among other things. Thanks !

**Comment by glguy** [comment]
@ekmett `v0.12.4` as previously tagged but not released doesn't satisfy cabal check. There're some minor commits just after that tag that I can incorporate into a new v0.12.4 tag and release. Sound good?

**Comment by ekmett** [comment]
Sure

**Comment by glguy** [comment]
[parsers-0.12.4](http://hackage.haskell.org/package/parsers-0.12.4) is on hackage
