### ISSUE TITLE
No instance for (Text.Parser.Combinators.Parsing Parser) arising from a use of `unexpected'

### ISSUE THREAD

**Issue by razvan-panda** [ekmett/parsers#72]
How to reproduce:

    checkout unexpected-bug-example branch from this fork: https://github.com/razvan-panda/parsers/tree/unexpected-bug-example

    stack init
    stack test

Causes following error:

    [1 of 2] Compiling SemVer           ( tests/SemVer.hs, .stack-work/dist/x86_64-linux-nix/Cabal-2.0.1.0/build/quickcheck/quickcheck-tmp/SemVer.o )
                
    /home/neo/Forks/parsers/tests/SemVer.hs:13:10: error:
        * No instance for (Text.Parser.Combinators.Parsing Parser)
            arising from a use of `unexpected'
        There are instances for similar types:
            instance Data.Attoparsec.Internal.Types.Chunk t =>
                    Text.Parser.Combinators.Parsing
                    (Data.Attoparsec.Internal.Types.Parser t)
            -- Defined in `Text.Parser.Combinators'
        * In the expression: unexpected "Leading Zeros"
        In a stmt of a 'do' block:
            if length digits > 1 && head digits == '0' then
                unexpected "Leading Zeros"
            else 
                return $ read digits
        In the expression:
            do digits <- some digit
            if length digits > 1 && head digits == '0' then
                unexpected "Leading Zeros"
            else
                return $ read digits
    |         
    13 |     then unexpected "Leading Zeros"
    |

**Comment by RyanGlScott** [comment]
This is a `Cabal` issue, not a `parsers` issue. The advice in https://github.com/ekmett/parsers/issues/73#issuecomment-378596056 contains a workaround.
